let recognition = null;
let numbersList = [];
window.SpeechRecognition = window.webkitSpeechRecognition || window.SpeechRecognition;

let isListening = false;
let currentLanguage = "en";
let pendingExportType = null;
let wakeLock = null;
let isWakeLockEnabled = false;
let shouldRestartRecognition = false;

const contentWrap = document.getElementById("contentWrap");
const recordBtn = document.getElementById("recordBtn");
const recordBtnLabel = document.getElementById("recordBtnLabel");
const recordIcon = document.getElementById("recordIcon");
const statusText = document.getElementById("statusText");
const langToggle = document.getElementById("langToggle");
const keyFileInput = document.getElementById("keyFile");
const importJsonInput = document.getElementById("importJson");
const exportBtn = document.getElementById("exportBtn");
const resetBtn = document.getElementById("resetBtn");
const rows = document.getElementById("rows");
const emptyState = document.getElementById("emptyState");
const progressCount = document.getElementById("progressCount");
const progressFill = document.getElementById("progressFill");
const progressCheckedLabel = document.getElementById("progressCheckedLabel");
const debugToggle = document.getElementById("debugToggle");
const debugPanel = document.getElementById("debugPanel");
const randomCheckBtn = document.getElementById("randomCheck");
const output = document.getElementById("output");
const wakeLockAPIAvailable = document.getElementById("wakeLockAPIAvailable");

const exportFormatModal = document.getElementById("exportFormatModal");
const commentModal = document.getElementById("commentModal");
const exportJsonBtn = document.getElementById("exportJsonBtn");
const exportPdfBtn = document.getElementById("exportPdfBtn");
const exportFormatCancel = document.getElementById("exportFormatCancel");
const commentCancel = document.getElementById("commentCancel");
const commentConfirm = document.getElementById("commentConfirm");
const commentList = document.getElementById("commentList");


const translations = {
  en: {
    htmlLang: "en",
    speechLang: "en-US",
    locale: "en-US",
    sessionStatus: "Session Status",
    listening: "Listening...",
    readyToRecord: "Ready to record",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    progress: "Progress",
    checked: "Checked",
    reset: "Reset",
    key: "Key",
    keyTitle: "Load key",
    export: "Export",
    exportTitle: "Export",
    import: "Import",
    importTitle: "Import JSON",
    number: "No",
    place: "Place",
    check: "Check",
    empty: "No markers recorded yet. Load a key to begin.",
    random50: "Random 50%",
    consoleLog: "Console Log",
    wakeLockSupported: "Wake Lock is supported",
    wakeLockNotSupported: "Wake Lock is not supported",
    keyNoValidNumbers: "The key file contains no valid numbers.",
    keyReadError: "The key file could not be read.",
    keyLoaded: count => `Key loaded: ${count} numbers.`,
    keyLoadedWithPlaces: count => `Key loaded: ${count} numbers with saved places.`,
    loadKeyFirst: "Please load a key first.",
    allNumbersChecked: "All numbers are already checked.",
    importedSession: date => `Imported session from ${date || "unknown date"}`,
    invalidJson: "Invalid JSON file.",
    speechNotSupported: "Speech recognition is not supported in this browser.",
    exportFormatTitle: "Export Format",
    exportFormatText: "Choose the export format:",
    cancel: "Cancel",
    confirm: "Confirm",
    commentModalTitle: "Unchecked Numbers",
    commentModalText: "Please provide a reason for each unchecked number before exporting.",
    commentPlaceholder: "Reason...",
    defaultUncheckedReason: "Not triggered",
    noComment: "No comment",
    pdfTitle: "MelderCheck™ - Official Export Document",
    pdfSubtitle: "Detector Test",
    pdfDate: date => `Date: ${date}`,
    pdfIntro: "This document was automatically generated by MelderCheck™ and documents the status of the detector numbers.",
    pdfHeaderNumber: "Detector No.",
    pdfHeaderOrt: "Place",
    pdfHeaderStatus: "Status",
    pdfHeaderComment: "Comment",
    pdfTriggered: "Triggered",
    pdfNotTriggered: "Not triggered",
    pdfCreatedAt: date => `Created on ${date}`,
    pdfPage: (page, total) => `Page ${page} of ${total}`,
    exportFileName: dateStr => `detector-test-${dateStr}`,
    commentLabelPrefix: "No."
  },
  de: {
    htmlLang: "de",
    speechLang: "de-DE",
    locale: "de-DE",
    sessionStatus: "Sitzungsstatus",
    listening: "Hört zu...",
    readyToRecord: "Bereit zur Aufnahme",
    startRecording: "Aufnahme starten",
    stopRecording: "Aufnahme stoppen",
    progress: "Fortschritt",
    checked: "Geprüft",
    reset: "Zurücksetzen",
    key: "Key",
    keyTitle: "Key laden",
    export: "Export",
    exportTitle: "Export",
    import: "Importieren",
    importTitle: "JSON importieren",
    number: "Nr",
    place: "Ort",
    check: "Prüfen",
    empty: "Noch keine Marker vorhanden. Lade zuerst einen Key.",
    random50: "Zufällige 50%",
    consoleLog: "Konsolenprotokoll",
    wakeLockSupported: "Wake Lock wird unterstützt",
    wakeLockNotSupported: "Wake Lock wird nicht unterstützt",
    keyNoValidNumbers: "Die Key-Datei enthält keine gültigen Nummern.",
    keyReadError: "Key-Datei konnte nicht gelesen werden.",
    keyLoaded: count => `Key geladen: ${count} Nummern.`,
    keyLoadedWithPlaces: count => `Key geladen: ${count} Nummern mit gespeicherten Orten.`,
    loadKeyFirst: "Bitte zuerst einen Key laden.",
    allNumbersChecked: "Alle Nummern sind bereits markiert.",
    importedSession: date => `Importierte Sitzung vom ${date || "unbekannten Datum"}`,
    invalidJson: "Ungültige JSON-Datei.",
    speechNotSupported: "Spracherkennung wird in diesem Browser nicht unterstützt.",
    exportFormatTitle: "Exportformat",
    exportFormatText: "Wählen Sie das Exportformat:",
    cancel: "Abbrechen",
    confirm: "Bestätigen",
    commentModalTitle: "Nicht geprüfte Nummern",
    commentModalText: "Bitte geben Sie vor dem Export für jede nicht geprüfte Nummer einen Grund an.",
    commentPlaceholder: "Grund...",
    defaultUncheckedReason: "Nicht ausgelöst",
    noComment: "Kein Kommentar",
    pdfTitle: "MelderCheck™ - Offizielles Exportdokument",
    pdfSubtitle: "Melder-Probe",
    pdfDate: date => `Datum: ${date}`,
    pdfIntro: "Mit diesem Dokument dokumentiert MelderCheck™ den Prüfstatus der Melder-Nummern.",
    pdfHeaderNumber: "Melder Nr.",
    pdfHeaderOrt: "Ort",
    pdfHeaderStatus: "Status",
    pdfHeaderComment: "Kommentar",
    pdfTriggered: "Ausgelöst",
    pdfNotTriggered: "Nicht ausgelöst",
    pdfCreatedAt: date => `Erstellt am ${date}`,
    pdfPage: (page, total) => `Seite ${page} von ${total}`,
    exportFileName: dateStr => `bewegungsmelder-test-${dateStr}`,
    commentLabelPrefix: "Nr."
  }
};

const wordToNumber = {
  one: 1, won: 1, two: 2, to: 2, too: 2, three: 3, four: 4, for: 4, five: 5, six: 6, seven: 7, eight: 8, ate: 8, nine: 9, ten: 10,
  eleven: 11, twelve: 12, thirteen: 13, fourteen: 14, fifteen: 15, sixteen: 16, seventeen: 17, eighteen: 18, nineteen: 19, twenty: 20,
  thirty: 30, forty: 40, fourty: 40, fifty: 50, sixty: 60, seventy: 70, eighty: 80, ninety: 90, hundred: 100,
  ein: 1, eins: 1, zwei: 2, drei: 3, vier: 4, fünf: 5, fuenf: 5, sechs: 6, sieben: 7, acht: 8, neun: 9, zehn: 10,
  elf: 11, zwölf: 12, zwoelf: 12, dreizehn: 13, vierzehn: 14, fünfzehn: 15, fuenfzehn: 15, sechzehn: 16, siebzehn: 17, achtzehn: 18,
  neunzehn: 19, zwanzig: 20, dreißig: 30, dreissig: 30, vierzig: 40, fünfzig: 50, fuenfzig: 50, sechzig: 60, siebzig: 70, achtzig: 80,
  neunzig: 90, hundert: 100
};

function t() {
  return translations[currentLanguage];
}

function normalizeTranscript(text) {
  return text
    .toLowerCase()
    .split(/\s+/)
    .map(word => wordToNumber[word] !== undefined ? wordToNumber[word] : word)
    .join(" ");
}

function syncModalScrollLock() {
  const anyOpen = document.querySelector("dialog[open]");
  document.documentElement.classList.toggle("modal-open", !!anyOpen);
}

document.querySelectorAll("dialog").forEach(dialog => {
  dialog.addEventListener("close", syncModalScrollLock);
  dialog.addEventListener("cancel", syncModalScrollLock);
});

function normalizeEntry(entry) {
  if (typeof entry === "object" && entry !== null) {
    return {
      number: Number(entry.number),
      ort: String(entry.ort || ""),
      checked: Boolean(entry.checked),
      comment: String(entry.comment || "")
    };
  }

  return {
    number: Number(entry),
    ort: "",
    checked: false,
    comment: ""
  };
}

function getEntries() {
  return numbersList
    .map(normalizeEntry)
    .filter(entry => !Number.isNaN(entry.number))
    .sort((a, b) => a.number - b.number);
}

function setEntries(entries) {
  numbersList = entries
    .map(entry => ({
      number: Number(entry.number),
      ort: String(entry.ort || ""),
      checked: Boolean(entry.checked),
      comment: String(entry.comment || "")
    }))
    .filter(entry => !Number.isNaN(entry.number))
    .sort((a, b) => a.number - b.number);
}

function updateStatus() {
  statusText.textContent = isListening ? t().listening : t().readyToRecord;
  recordBtnLabel.textContent = isListening ? t().stopRecording : t().startRecording;

  recordIcon.classList.remove("fa-circle-stop", "fa-circle");
  recordIcon.classList.add(isListening ? "fa-circle-stop" : "fa-circle");

  contentWrap.classList.toggle("recording", isListening);
  contentWrap.classList.toggle("status-idle", !isListening);
}

function updateProgress() {
  const entries = getEntries();
  const total = entries.length;
  const checked = entries.filter(entry => {
    const cb = document.getElementById(`check-${entry.number}`);
    return cb && cb.checked;
  }).length;

  progressCount.textContent = `${checked}/${total}`;
  progressCheckedLabel.textContent = t().checked;

  const percent = total ? (checked / total) * 100 : 0;
  progressFill.style.width = `${percent}%`;
  progressFill.style.background =
    checked === total && total > 0
      ? "linear-gradient(90deg, #f5c400, #ffe066)"
      : "linear-gradient(90deg, #a6f7c3 0%, #63e7a1 100%)";
}

function updateEmptyState() {
  const hasEntries = getEntries().length > 0;
  emptyState.classList.toggle("active", !hasEntries);
  rows.classList.toggle("active", hasEntries);
}

function applyLanguage() {
  langToggle.dataset.lang = currentLanguage;
  document.documentElement.lang = t().htmlLang;
  document.title = "AudioMarker";

  document.querySelectorAll("[data-i18n]").forEach(element => {
    const key = element.dataset.i18n;
    if (t()[key]) {
      element.textContent = t()[key];
    }
  });

  document.getElementById("keyLabel").title = t().keyTitle;
  document.getElementById("importLabel").title = t().importTitle;
  exportBtn.title = t().exportTitle;
  randomCheckBtn.textContent = t().random50;
  document.getElementById("consoleLog").textContent = t().consoleLog;
  wakeLockAPIAvailable.textContent = "wakeLock" in navigator ? t().wakeLockSupported : t().wakeLockNotSupported;
  document.getElementById("exportFormatTitle").textContent = t().exportFormatTitle;
  document.getElementById("exportFormatText").textContent = t().exportFormatText;
  exportJsonBtn.textContent = "JSON";
  exportPdfBtn.textContent = "PDF";
  exportFormatCancel.textContent = t().cancel;
  document.getElementById("commentModalTitle").textContent = t().commentModalTitle;
  document.getElementById("commentModalText").textContent = t().commentModalText;
  commentCancel.textContent = t().cancel;
  commentConfirm.textContent = t().confirm;

  updateStatus();
  renderRows();
  updateProgress();
}

function vibrate() {
  if ("vibrate" in navigator) navigator.vibrate(50);
}

function playSuccessSound() {
  const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  const oscillator = audioCtx.createOscillator();
  const gainNode = audioCtx.createGain();

  oscillator.connect(gainNode);
  gainNode.connect(audioCtx.destination);
  oscillator.type = "sine";
  oscillator.frequency.setValueAtTime(880, audioCtx.currentTime);
  oscillator.frequency.setValueAtTime(1100, audioCtx.currentTime + 0.1);
  gainNode.gain.setValueAtTime(0.4, audioCtx.currentTime);
  gainNode.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.4);

  oscillator.start(audioCtx.currentTime);
  oscillator.stop(audioCtx.currentTime + 0.4);
}

function playUnrecognizedSound() {
  const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
  const oscillator = audioCtx.createOscillator();
  const gainNode = audioCtx.createGain();

  oscillator.connect(gainNode);
  gainNode.connect(audioCtx.destination);
  oscillator.type = "sawtooth";
  oscillator.frequency.setValueAtTime(300, audioCtx.currentTime);
  oscillator.frequency.setValueAtTime(200, audioCtx.currentTime + 0.15);
  gainNode.gain.setValueAtTime(0.3, audioCtx.currentTime);
  gainNode.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.4);

  oscillator.start(audioCtx.currentTime);
  oscillator.stop(audioCtx.currentTime + 0.4);
}

function renderRows() {
  const entries = getEntries();
  rows.innerHTML = "";

  if (!entries.length) {
    updateEmptyState();
    updateProgress();
    return;
  }

  entries.forEach(entry => {
    const row = document.createElement("div");
    row.className = "table-row";
    row.dataset.number = String(entry.number);

    const numberCell = document.createElement("div");
    numberCell.className = "row-number";
    numberCell.textContent = entry.number;

    const locationCell = document.createElement("div");
    const locationInput = document.createElement("input");
    locationInput.type = "text";
    locationInput.className = "location-input";
    locationInput.dataset.number = String(entry.number);
    locationInput.value = entry.ort || "";
    locationInput.placeholder = t().place;
    locationInput.autocomplete = "off";
    locationInput.addEventListener("input", e => {
      const number = Number(e.target.dataset.number);
      const found = numbersList.find(item => typeof item === "object" && item.number === number);
      if (found) found.ort = e.target.value;
    });
    locationCell.appendChild(locationInput);

    const checkCell = document.createElement("div");
    checkCell.className = "check-wrap";
    const checkbox = document.createElement("input");
    checkbox.type = "checkbox";
    checkbox.className = "row-checkbox";
    checkbox.id = `check-${entry.number}`;
    checkbox.checked = entry.checked;
    checkbox.addEventListener("change", () => {
      row.classList.toggle("checked-row", checkbox.checked);
      const found = numbersList.find(item => typeof item === "object" && item.number === entry.number);
      if (found) found.checked = checkbox.checked;
      updateProgress();
    });
    row.classList.toggle("checked-row", checkbox.checked);
    checkCell.appendChild(checkbox);

    row.appendChild(numberCell);
    row.appendChild(locationCell);
    row.appendChild(checkCell);
    rows.appendChild(row);
  });

  updateEmptyState();
  updateProgress();
}

function parseKeyText(text) {
  const tokens = text.split(/[\s,;]+/).map(token => token.trim()).filter(Boolean);
  const parsed = tokens
    .map(token => parseInt(token, 10))
    .filter(number => !Number.isNaN(number));

  const unique = [...new Set(parsed)].sort((a, b) => a - b);
  return unique.map(number => ({
    number,
    ort: "",
    checked: false,
    comment: ""
  }));
}

function importJsonData(data) {
  if (Array.isArray(data)) {
    const entries = data
      .map(item => {
        if (typeof item === "number" || typeof item === "string") {
          const number = parseInt(item, 10);
          return Number.isNaN(number) ? null : { number, ort: "", checked: false, comment: "" };
        }
        if (item && typeof item === "object") {
          const number = parseInt(item.number, 10);
          if (Number.isNaN(number)) return null;
          return {
            number,
            ort: item.ort || "",
            checked: Boolean(item.checked),
            comment: item.comment || item.reason || ""
          };
        }
        return null;
      })
      .filter(Boolean);

    setEntries(entries);
    renderRows();
    return;
  }

  if (data && Array.isArray(data.numbers)) {
    const checkedMap = new Map();
    const uncheckedMap = new Map();

    if (Array.isArray(data.checked)) {
      data.checked.forEach(item => {
        if (typeof item === "object" && item !== null) {
          checkedMap.set(Number(item.number), item);
        } else {
          checkedMap.set(Number(item), { number: Number(item), ort: "" });
        }
      });
    }

    if (Array.isArray(data.unchecked)) {
      data.unchecked.forEach(item => {
        if (item && typeof item === "object") {
          uncheckedMap.set(Number(item.number), item);
        }
      });
    }

    const entries = data.numbers.map(item => {
      if (typeof item === "object" && item !== null) {
        const number = Number(item.number);
        return {
          number,
          ort: String(item.ort || ""),
          checked: checkedMap.has(number),
          comment: uncheckedMap.get(number)?.reason || ""
        };
      }

      const number = Number(item);
      return {
        number,
        ort: checkedMap.get(number)?.ort || uncheckedMap.get(number)?.ort || "",
        checked: checkedMap.has(number),
        comment: uncheckedMap.get(number)?.reason || ""
      };
    }).filter(entry => !Number.isNaN(entry.number));

    setEntries(entries);
    renderRows();
    return;
  }

  throw new Error("invalid-json");
}

function ensureRecognition() {
  if (recognition) return recognition;
  if (!(window.SpeechRecognition || window.webkitSpeechRecognition)) return null;

  recognition = new (window.SpeechRecognition || window.webkitSpeechRecognition)();
  recognition.continuous = true;
  recognition.interimResults = false;
  recognition.lang = t().speechLang;

  recognition.onresult = event => {
    const result = event.results[event.results.length - 1][0].transcript;
    output.textContent = result;
    markNumberAsChecked(result);
  };

  recognition.onend = () => {
    if (shouldRestartRecognition && isListening) {
      setTimeout(() => {
        try {
          recognition.lang = t().speechLang;
          recognition.start();
        } catch {}
      }, 150);
    }
  };

  recognition.onerror = () => {};

  return recognition;
}

async function toggleRecognition() {
  if (!numbersList.length) {
    alert(t().loadKeyFirst);
    return;
  }

  const instance = ensureRecognition();
  if (!instance) {
    alert(t().speechNotSupported);
    return;
  }

  if (!isListening) {
    try {
      instance.lang = t().speechLang;
      shouldRestartRecognition = true;
      instance.start();
      isListening = true;
    } catch {}
  } else {
    shouldRestartRecognition = false;
    isListening = false;
    try {
      instance.stop();
    } catch {}
  }

  updateStatus();
}

function toggleLanguage() {
  currentLanguage = currentLanguage === "en" ? "de" : "en";
  applyLanguage();

  if (recognition) {
    recognition.lang = t().speechLang;
  }

  if (isListening && recognition) {
    shouldRestartRecognition = false;
    try {
      recognition.stop();
    } catch {}

    setTimeout(() => {
      if (isListening && recognition) {
        try {
          recognition.lang = t().speechLang;
          shouldRestartRecognition = true;
          recognition.start();
        } catch {}
      }
    }, 200);
  }
}

function markNumberAsChecked(text) {
  const normalizedText = normalizeTranscript(text);
  const numbers = normalizedText.match(/\d+/g);
  let matched = false;

  if (numbers) {
    for (const numberStr of numbers) {
      const number = parseInt(numberStr, 10);
      const exists = getEntries().some(entry => entry.number === number);

      if (!Number.isNaN(number) && exists) {
        const checkbox = document.getElementById(`check-${number}`);
        if (checkbox && !checkbox.checked) {
          checkbox.checked = true;
          checkbox.closest(".table-row")?.classList.add("checked-row");
          const found = numbersList.find(item => typeof item === "object" && item.number === number);
          if (found) found.checked = true;
          playSuccessSound();
          vibrate();
          checkbox.closest(".table-row")?.scrollIntoView({ behavior: "smooth", block: "center" });
          updateProgress();
          matched = true;
        }
      }
    }
  }

  if (!matched) playUnrecognizedSound();
}

function toggleDebugTools() {
  debugPanel.classList.toggle("hidden");
  randomCheckBtn.classList.toggle("hidden");
}

function syncOrtValuesFromInputs() {
  const inputs = document.querySelectorAll(".location-input[data-number]");
  inputs.forEach(input => {
    const number = parseInt(input.dataset.number, 10);
    if (Number.isNaN(number)) return;

    const item = numbersList.find(entry => typeof entry === "object" && entry.number === number);
    if (item) {
      item.ort = input.value.trim();
    }
  });
}

function buildSessionData(comments = {}) {
  syncOrtValuesFromInputs();

  const now = new Date();
  const checked = [];
  const unchecked = [];
  const entries = getEntries();

  for (const entry of entries) {
    const cb = document.getElementById(`check-${entry.number}`);
    const isCheckedEntry = !!(cb && cb.checked);

    if (isCheckedEntry) {
      checked.push({
        number: entry.number,
        ort: entry.ort
      });
    } else {
      unchecked.push({
        number: entry.number,
        ort: entry.ort,
        reason: comments[entry.number] ?? entry.comment ?? ""
      });
    }
  }

  return {
    language: currentLanguage,
    exportedAt: now.toISOString(),
    exportedAtReadable: now.toLocaleString(t().locale),
    complete: unchecked.length === 0,
    numbers: entries.map(entry => ({
      number: entry.number,
      ort: entry.ort
    })),
    checked,
    unchecked
  };
}

function doExportJSON(comments = {}) {
  const data = buildSessionData(comments);
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const dateStr = new Date().toISOString().slice(0, 10);

  a.href = url;
  a.download = `${t().exportFileName(dateStr)}.json`;
  a.click();

  URL.revokeObjectURL(url);
}

function doExportPDF(comments = {}) {
  const data = buildSessionData(comments);
  const lang = translations[data.language] || t();
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const marginBottom = 15;
  const marginTop = 20;
  const marginLeft = 16;
  const marginRight = 16;

  const colNumber = 20;
  const colOrt = 42;
  const colStatus = 94;
  const colComment = 138;

  function addHeader(yPosition) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(lang.pdfHeaderNumber, colNumber, yPosition);
    doc.text(lang.pdfHeaderOrt, colOrt, yPosition);
    doc.text(lang.pdfHeaderStatus, colStatus, yPosition);
    doc.text(lang.pdfHeaderComment, colComment, yPosition);
    doc.setLineWidth(0.5);
    doc.line(marginLeft, yPosition + 2, pageWidth - marginRight, yPosition + 2);
    doc.setFont("helvetica", "normal");
    return yPosition + 8;
  }

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(lang.pdfTitle, 105, 20, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(lang.pdfSubtitle, 105, 28, { align: "center" });
  doc.text(lang.pdfDate(data.exportedAtReadable), 105, 35, { align: "center" });

  doc.setFontSize(10);
  doc.text(lang.pdfIntro, 20, 45);

  let yPos = addHeader(55);

  const allRows = [
    ...data.checked.map(item => ({
      number: item.number,
      ort: item.ort || "",
      status: `✓ ${lang.pdfTriggered}`,
      comment: "—"
    })),
    ...data.unchecked.map(item => ({
      number: item.number,
      ort: item.ort || "",
      status: `✗ ${lang.pdfNotTriggered}`,
      comment: item.reason || lang.noComment
    }))
  ];

  for (const row of allRows) {
    const ortLines = doc.splitTextToSize(row.ort || "—", 40);
    const statusLines = doc.splitTextToSize(row.status, 34);
    const commentLines = doc.splitTextToSize(row.comment, 46);

    const lineCount = Math.max(ortLines.length, statusLines.length, commentLines.length, 1);
    const rowHeight = Math.max(7, lineCount * 4.6);

    if (yPos + rowHeight > pageHeight - marginBottom) {
      doc.addPage();
      yPos = addHeader(marginTop);
    }

    doc.text(String(row.number), colNumber, yPos);
    doc.text(ortLines, colOrt, yPos);
    doc.text(statusLines, colStatus, yPos);
    doc.text(commentLines, colComment, yPos);

    yPos += rowHeight;
  }

  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text(lang.pdfCreatedAt(data.exportedAtReadable), 20, pageHeight - 10);
    doc.text(lang.pdfPage(i, totalPages), pageWidth - 20, pageHeight - 10, { align: "right" });
  }

  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`${lang.exportFileName(dateStr)}.pdf`);
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&#39;");
}

function openCommentModal() {
  syncOrtValuesFromInputs();

  const unchecked = getEntries().filter(entry => {
    const cb = document.getElementById(`check-${entry.number}`);
    return !(cb && cb.checked);
  });

  commentList.innerHTML = unchecked.map(entry => `
    <div class="comment-row">
      <label data-number="${entry.number}" for="comment-${entry.number}">
        ${t().commentLabelPrefix} ${entry.number}
      </label>
      <input
        id="comment-${entry.number}"
        type="text"
        value="${escapeHtml(entry.comment || "")}"
        placeholder="${escapeHtml(t().commentPlaceholder)}"
      />
    </div>
  `).join("");

  commentModal.showModal();
  syncModalScrollLock();
}

async function requestWakeLock() {
  if (!("wakeLock" in navigator)) return;

  try {
    wakeLock = await navigator.wakeLock.request("screen");
    isWakeLockEnabled = true;

    wakeLock.addEventListener("release", () => {
      isWakeLockEnabled = false;
    });
  } catch {}
}

async function releaseWakeLock() {
  if (!wakeLock) return;

  try {
    await wakeLock.release();
  } catch {}

  wakeLock = null;
  isWakeLockEnabled = false;
}

async function toggleWakeLock() {
  if (!("wakeLock" in navigator)) return;

  if (!isWakeLockEnabled) {
    await requestWakeLock();
  } else {
    await releaseWakeLock();
  }
}

keyFileInput?.addEventListener("change", event => {
  const file = event.target.files[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = e => {
    try {
      const text = String(e.target.result || "").trim();

      if (file.name.toLowerCase().endsWith(".json")) {
        const data = JSON.parse(text);
        importJsonData(data);
        const hasPlaces = getEntries().some(entry => entry.ort);
        alert(hasPlaces ? t().keyLoadedWithPlaces(numbersList.length) : t().keyLoaded(numbersList.length));
      } else {
        const parsedNumbers = parseKeyText(text);
        if (!parsedNumbers.length) {
          alert(t().keyNoValidNumbers);
          return;
        }
        setEntries(parsedNumbers);
        renderRows();
        alert(t().keyLoaded(numbersList.length));
      }
    } catch {
      alert(t().keyReadError);
    }
  };

  reader.readAsText(file);
  event.target.value = "";
});

importJsonInput?.addEventListener("change", event => {
  const file = event.target.files[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = e => {
    try {
      const data = JSON.parse(String(e.target.result || ""));
      if (data.language && translations[data.language]) {
        currentLanguage = data.language;
      }
      importJsonData(data);
      applyLanguage();
      alert(t().importedSession(data.exportedAtReadable));
    } catch {
      alert(t().invalidJson);
    }
  };

  reader.readAsText(file);
  event.target.value = "";
});

recordBtn?.addEventListener("click", async () => {
  await toggleWakeLock();
  await toggleRecognition();
});

langToggle?.addEventListener("click", toggleLanguage);

resetBtn?.addEventListener("click", () => {
  numbersList.forEach(item => {
    if (typeof item === "object" && item !== null) {
      item.checked = false;
    }
  });

  getEntries().forEach(entry => {
    const checkbox = document.getElementById(`check-${entry.number}`);
    if (checkbox && checkbox.checked) {
      checkbox.checked = false;
      checkbox.closest(".table-row")?.classList.remove("checked-row");
    }
  });

  updateProgress();
});

randomCheckBtn?.addEventListener("click", () => {
  const entries = getEntries();

  const uncheckedEntries = entries.filter(entry => {
    const checkbox = document.getElementById(`check-${entry.number}`);
    return !(checkbox && checkbox.checked);
  });

  if (!uncheckedEntries.length) {
    alert(t().allNumbersChecked);
    return;
  }

  const shuffled = [...uncheckedEntries].sort(() => Math.random() - 0.5);
  const targetCount = Math.max(1, Math.ceil(uncheckedEntries.length / 2));
  const toCheck = shuffled.slice(0, targetCount);

  toCheck.forEach(entry => {
    const checkbox = document.getElementById(`check-${entry.number}`);
    if (checkbox && !checkbox.checked) {
      checkbox.checked = true;
      checkbox.closest(".table-row")?.classList.add("checked-row");
    }

    const found = numbersList.find(item => typeof item === "object" && item.number === entry.number);
    if (found) {
      found.checked = true;
    }
  });

  updateProgress();
});

debugToggle?.addEventListener("click", toggleDebugTools);

exportBtn?.addEventListener("click", () => {
  if (!numbersList.length) {
    alert(t().loadKeyFirst);
    return;
  }

  exportFormatModal.showModal();
  syncModalScrollLock();
});

exportFormatCancel?.addEventListener("click", () => {
  exportFormatModal.close();
});

exportJsonBtn?.addEventListener("click", () => {
  exportFormatModal.close();

  const allChecked = getEntries().every(entry => {
    const cb = document.getElementById(`check-${entry.number}`);
    return cb && cb.checked;
  });

  if (allChecked) {
    doExportJSON();
  } else {
    pendingExportType = "json";
    openCommentModal();
  }
});

exportPdfBtn?.addEventListener("click", () => {
  exportFormatModal.close();

  const allChecked = getEntries().every(entry => {
    const cb = document.getElementById(`check-${entry.number}`);
    return cb && cb.checked;
  });

  if (allChecked) {
    doExportPDF();
  } else {
    pendingExportType = "pdf";
    openCommentModal();
  }
});

commentCancel?.addEventListener("click", () => {
  commentModal.close();
  pendingExportType = null;
});

commentConfirm?.addEventListener("click", () => {
  const comments = {};

  getEntries().forEach(entry => {
    const input = document.getElementById(`comment-${entry.number}`);
    if (input) {
      comments[entry.number] = input.value.trim();
      const found = numbersList.find(item => typeof item === "object" && item.number === entry.number);
      if (found) found.comment = comments[entry.number];
    }
  });

  commentModal.close();

  if (pendingExportType === "json") {
    doExportJSON(comments);
  } else if (pendingExportType === "pdf") {
    doExportPDF(comments);
  }

  pendingExportType = null;
});

document.addEventListener("pointerdown", event => {
  const button = event.target.closest(".pressable");
  if (button) button.classList.add("is-pressed");
});

document.addEventListener("pointerup", () => {
  document.querySelectorAll(".pressable.is-pressed").forEach(button => {
    button.classList.remove("is-pressed");
  });
});

document.addEventListener("pointercancel", () => {
  document.querySelectorAll(".pressable.is-pressed").forEach(button => {
    button.classList.remove("is-pressed");
  });
});

document.addEventListener("visibilitychange", async () => {
  if (document.visibilityState === "visible" && isListening && "wakeLock" in navigator && !isWakeLockEnabled) {
    await requestWakeLock();
  }
});

applyLanguage();
renderRows();
updateStatus();
